name: Guardrail Example

on:
  workflow_dispatch:

jobs:
  guardrail-bad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Guardrail (bad fixtures)
        uses: ./.github/actions/guardrail
        with:
          path: examples/fixtures/terraform/bad
          state: examples/fixtures/state/bad.tfstate
          schema: true
          fail_on: medium
          install_source: repo
      - name: Export JSON
        run: |
          terraform-guardrail scan examples/fixtures/terraform/bad \
            --state examples/fixtures/state/bad.tfstate \
            --schema \
            --format json > guardrail-report.json
      - name: Build SARIF and JUnit
        run: |
          python - <<'PY'
          import json
          import xml.etree.ElementTree as ET

          with open("guardrail-report.json", encoding="utf-8") as handle:
              report = json.load(handle)

          def to_level(severity: str) -> str:
              if severity == "high":
                  return "error"
              if severity == "medium":
                  return "warning"
              return "note"

          findings = report.get("findings", [])
          rules = {}
          results = []
          for finding in findings:
              rule_id = finding.get("rule_id", "UNKNOWN")
              rules.setdefault(rule_id, {"id": rule_id, "name": rule_id})
              result = {
                  "ruleId": rule_id,
                  "level": to_level(finding.get("severity", "low")),
                  "message": {"text": finding.get("message", "")},
              }
              path = finding.get("path")
              if path:
                  result["locations"] = [
                      {"physicalLocation": {"artifactLocation": {"uri": path}}}
                  ]
              results.append(result)

          sarif = {
              "version": "2.1.0",
              "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
              "runs": [
                  {
                      "tool": {
                          "driver": {
                              "name": "Terraform Guardrail MCP",
                              "informationUri": "https://github.com/Huzefaaa2/terraform-guardrail",
                              "rules": list(rules.values()),
                          }
                      },
                      "results": results,
                  }
              ],
          }

          with open("guardrail-report.sarif", "w", encoding="utf-8") as handle:
              json.dump(sarif, handle, indent=2)

          testsuite = ET.Element("testsuite", name="terraform-guardrail")
          testsuite.set("tests", str(len(findings)))
          failures = sum(1 for f in findings if f.get("severity") in {"high", "medium"})
          skipped = sum(1 for f in findings if f.get("severity") == "low")
          testsuite.set("failures", str(failures))
          testsuite.set("skipped", str(skipped))

          for finding in findings:
              rule_id = finding.get("rule_id", "UNKNOWN")
              message = finding.get("message", "")
              path = finding.get("path", "")
              testcase = ET.SubElement(testsuite, "testcase", classname=rule_id, name=message)
              detail = f"{message}"
              if path:
                  detail = f"{message} ({path})"
              if finding.get("severity") == "low":
                  ET.SubElement(testcase, "skipped", message=detail)
              else:
                  failure = ET.SubElement(testcase, "failure", message=detail)
                  failure.text = detail

          tree = ET.ElementTree(testsuite)
          tree.write("guardrail-report.junit.xml", encoding="utf-8", xml_declaration=True)
          PY
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: guardrail-bad-outputs
          path: |
            guardrail-report.json
            guardrail-report.sarif
            guardrail-report.junit.xml

  guardrail-good:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Guardrail (good fixtures)
        uses: ./.github/actions/guardrail
        with:
          path: examples/fixtures/terraform/good
          schema: true
          fail_on: high
          install_source: repo
