name: "Terraform Guardrail MCP"
description: "Run Terraform Guardrail scans in CI for pre-apply checks."
inputs:
  path:
    description: "Path to Terraform files or directory"
    default: "."
  state:
    description: "Optional path to a .tfstate file"
    default: ""
  schema:
    description: "Enable schema-aware validation (true/false)"
    default: "false"
  fail_on:
    description: "Fail if findings at/above severity: low, medium, high"
    default: "high"
  policy_bundle:
    description: "Policy bundle ID to evaluate"
    default: ""
  policy_bundle_path:
    description: "Local policy bundle path (.tar.gz or directory)"
    default: ""
  policy_registry:
    description: "Policy registry URL"
    default: ""
  policy_query:
    description: "OPA query override"
    default: ""
  opa_version:
    description: "OPA version to install (e.g. v0.63.0 or latest)"
    default: "latest"
  install_source:
    description: "Install source: pypi or repo"
    default: "pypi"
  python_version:
    description: "Python version for the action"
    default: "3.11"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install Terraform Guardrail
      shell: bash
      run: |
        if [ "${{ inputs.install_source }}" = "repo" ]; then
          python -m pip install -e ".[dev]"
        else
          python -m pip install terraform-guardrail
        fi
    - name: Cache OPA
      if: ${{ inputs.policy_bundle != '' || inputs.policy_bundle_path != '' }}
      uses: actions/cache@v4
      with:
        path: ~/.cache/opa
        key: opa-${{ runner.os }}-${{ inputs.opa_version }}
    - name: Install OPA binary
      if: ${{ inputs.policy_bundle != '' || inputs.policy_bundle_path != '' }}
      shell: bash
      run: |
        OPA_CACHE_DIR="$HOME/.cache/opa"
        OPA_BIN="$OPA_CACHE_DIR/opa"
        mkdir -p "$OPA_CACHE_DIR"
        ARCH="$(uname -m)"
        case "$ARCH" in
          x86_64) ARCH="amd64" ;;
          aarch64|arm64) ARCH="arm64" ;;
        esac
        if [ ! -x "$OPA_BIN" ]; then
          OPA_VERSION="${{ inputs.opa_version }}"
          if [ "$OPA_VERSION" = "latest" ]; then
            URL="https://openpolicyagent.org/downloads/latest/opa_linux_${ARCH}"
          else
            OPA_VERSION="${OPA_VERSION#v}"
            URL="https://openpolicyagent.org/downloads/v${OPA_VERSION}/opa_linux_${ARCH}"
          fi
          curl -sSL -o "$OPA_BIN" "$URL"
          chmod +x "$OPA_BIN"
        fi
        echo "$OPA_CACHE_DIR" >> "$GITHUB_PATH"
    - name: Run Guardrail scan
      shell: bash
      run: |
        args=(scan "${{ inputs.path }}")
        if [ -n "${{ inputs.state }}" ]; then
          args+=(--state "${{ inputs.state }}")
        fi
        if [ "${{ inputs.schema }}" = "true" ]; then
          args+=(--schema)
        fi
        if [ -n "${{ inputs.policy_bundle }}" ]; then
          args+=(--policy-bundle "${{ inputs.policy_bundle }}")
        fi
        if [ -n "${{ inputs.policy_bundle_path }}" ]; then
          args+=(--policy-bundle-path "${{ inputs.policy_bundle_path }}")
        fi
        if [ -n "${{ inputs.policy_registry }}" ]; then
          args+=(--policy-registry "${{ inputs.policy_registry }}")
        fi
        if [ -n "${{ inputs.policy_query }}" ]; then
          args+=(--policy-query "${{ inputs.policy_query }}")
        fi
        if [ -n "${{ inputs.fail_on }}" ]; then
          args+=(--fail-on "${{ inputs.fail_on }}")
        fi
        terraform-guardrail "${args[@]}"
